---
title: "Untitled"
author: "Anna"
date: "2024-03-26"
output: html_document
---

$$\begin{cases}
      \min{F(x)=10x_1+4x_2+8x_3+6x_4+2x_5+3x_6+8x_7+2x_8+6x_9+6x_{10}}\\
      x_1+x_2+x_3+x_4\leq400\\
      x_5+x_6\geq800\\
      x_7+x_8+x_9+x_{10}\leq600\\
      \sum_{i=1}^{10} x_i=1200\\
      \forall{i}: 0\leq x_i\leq700
\end{cases}\,$$

```{r}
library(lpSolve)
Fun <- c(10, 4, 8, 6, 2, 3, 8, 2, 6, 6)
```

```{r}
A <- rbind(c(1, 1, 1, 1, 0, 0, 0, 0, 0, 0), 
           c(0, 0, 0, 0, 1, 1, 0, 0, 0, 0), 
           c(0, 0, 0, 0, 0, 0, 1, 1, 1, 1),
           c(10, 4, 8, 6, -2, -3, 0, 0, 0, 0),
           c(1, 1, 1, 1, 1, 1, 1, 1, 1, 1),
           c(1, 1, 1, 1, 1, 1, 1, 1, 1, 1), 
           c(1, 0, 0, 0, 0, 0, 0, 0, 0, 0), 
           c(0, 1, 0, 0, 0, 0, 0, 0, 0, 0), 
           c(0, 0, 1, 0, 0, 0, 0, 0, 0, 0), 
           c(0, 0, 0, 1, 0, 0, 0, 0, 0, 0), 
           c(0, 0, 0, 0, 1, 0, 0, 0, 0, 0), 
           c(0, 0, 0, 0, 0, 1, 0, 0, 0, 0), 
           c(0, 0, 0, 0, 0, 0, 1, 0, 0, 0), 
           c(0, 0, 0, 0, 0, 0, 0, 1, 0, 0), 
           c(0, 0, 0, 0, 0, 0, 0, 0, 1, 0), 
           c(0, 0, 0, 0, 0, 0, 0, 0, 0, 1))
```

```{r}
B <- c(400, 800, 600, 0, 700, 1000, 700, 700, 700, 700, 700, 700, 700, 700, 700, 700)
CD <- c("<=", "<=", "<=","=",">=", "=", "<=", "<=", "<=", "<=", "<=", "<=", "<=", "<=", "<=", "<=")
```

```{r}
optimum <- lp(
  direction = "min",
  objective.in = Fun,
  const.mat = A,
  const.dir = CD,
  const.rhs = B,
  compute.sens = TRUE)
optimum
```

```{r}

optimum$solution

```

```{r}
optimum$sens.coef.from
optimum$sens.coef.to
```

```{r}
optimum$duals
optimum$duals.from
optimum$duals.to
```
